name: jetleaf_validation
description: Validation module for JetLeaf â€” provides data, input, and schema validation utilities.
version: 1.0.8

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_validation
issue_tracker: https://github.com/jetleaf/jetleaf_validation/issues
documentation: https://jetleaf.hapnium.com/docs/validation

topics:
  - validation
  - data
  - jetleaf
  - schema
  - rules

keywords:
  - jetleaf
  - validate
  - input
  - constraints
  - integrity

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.0.8
  jetleaf_logging: ^1.0.8
  jetleaf_core: ^1.0.9
  jetleaf_env: ^1.0.9

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0